#!/bin/sh

set -e

node_version="$1"

basedir="$( cd -P "$( dirname "$0" )" && pwd )"

# make a temp directory
cache_tempdir="$( mktemp -t libgd_cache )"
rm -rf $cache_tempdir
mkdir -p $cache_tempdir

tempdir="$( mktemp -t node_XXXX )"
rm -rf $tempdir
mkdir -p $tempdir
cd $tempdir

# download and extract node
curl http://nodejs.org/dist/node-v${node_version}.tar.gz -o node.tgz
tar xzvf node.tgz

cd node-v${node_version}

./configure --prefix=${cache_tempdir}/node-v${node_version} && make install
cd ${cache_tempdir}/node-v${node_version}
tar -zcvf ${cache_tempdir}/node-${node_version}.tgz .

cp $cache_tempdir/node-${node_version}.tgz /tmp/release/

# go into scons
cd ${tempdir}/node-v${node_version}/tools/scons

# package scons
scons_version=$(ls | grep "scons-local" | cut -d- -f3)
tar czvf $cache_tempdir/scons-${scons_version}.tgz *

cp $cache_tempdir/scons-${scons_version}.tgz /tmp/release/

# upload scons to s3
$basedir/aws/s3 put $S3_BUCKET \
  nodejs-${node_version}.tgz $cache_tempdir/node-${node_version}.tgz

$basedir/aws/s3 put $S3_BUCKET \
  scons-${scons_version}.tgz $cache_tempdir/scons-${scons_version}.tgz
