#!/bin/sh

set -e

node_version="$1"

#if [ "$node_version" == "" ]; then
#  echo "usage: $0 VERSION"
#  exit 1
#fi
#
#if [ "$AWS_ID" == "" ]; then
#  echo "must set AWS_ID"
#  exit 1
#fi
#
#if [ "$AWS_SECRET" == "" ]; then
#  echo "must set AWS_SECRET"
#  exit 1
#fi
#
#if [ "$S3_BUCKET" == "" ]; then
#  echo "must set S3_BUCKET"
#  exit 1
#fi

basedir="$( cd -P "$( dirname "$0" )" && pwd )"

# make a temp directory
cache_tempdir="$( mktemp -t libgd_cache )"
rm -rf $cache_tempdir
mkdir -p $cache_tempdir

tempdir="$( mktemp -t node_XXXX )"
rm -rf $tempdir
mkdir -p $tempdir
cd $tempdir

# download and extract node
curl http://nodejs.org/dist/node-v${node_version}.tar.gz -o node.tgz
tar xzvf node.tgz

cd node-v${node_version}

./configure --prefix=${cache_tempdir}/node-v${node_version} && make install
cd ${cache_tempdir}/node-v${node_version}
tar -zcvf ${cache_tempdir}/node-${node_version}.tgz .

$basedir/aws/s3 put $S3_BUCKET \
  nodejs-${node_version}.tgz $cache_tempdir/node-${node_version}.tgz

# go into scons
cd ${tempdir}/node-v${node_version}/tools/scons

# package scons
scons_version=$(ls | grep "scons-local" | cut -d- -f3)
tar czvf $cache_tempdir/scons-${scons_version}.tgz *

# upload scons to s3
$basedir/aws/s3 put $S3_BUCKET \
  scons-${scons_version}.tgz $cache_tempdir/scons-${scons_version}.tgz
