#!/bin/sh

set -e

npm_version="$1"

basedir="$( cd -P "$( dirname "$0" )" && pwd )"

# make a temp directory
tempdir="$( mktemp -t node_XXXX )"
rm -rf $tempdir
mkdir -p $tempdir
cd $tempdir

# download npm
git clone https://github.com/isaacs/npm.git

# go into npm dir
cd npm

# grab the right version
git checkout v${npm_version}
git submodule update --init --recursive

# package it up
tar czvf $tempdir/npm-${npm_version}.tgz *

cp $tempdir/npm-${npm_version}.tgz /tmp/release/

# upload npm to s3
$basedir/aws/s3 put $S3_BUCKET \
  npm-${npm_version}.tgz $tempdir/npm-${npm_version}.tgz
